/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuffetRouteImport } from './routes/buffet'
import { Route as ConversationsRouteImport } from './routes/conversations'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as EnquiriesRouteImport } from './routes/enquiries'
import { Route as FollowUpsRouteImport } from './routes/follow-ups'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as SettingsRouteImport } from './routes/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuffetRoute = BuffetRouteImport.update({
  id: '/buffet',
  path: '/buffet',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsRoute = ConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const EnquiriesRoute = EnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowUpsRoute = FollowUpsRouteImport.update({
  id: '/follow-ups',
  path: '/follow-ups',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buffet': typeof BuffetRoute
  '/conversations': typeof ConversationsRoute
  '/customers': typeof CustomersRoute
  '/enquiries': typeof EnquiriesRoute
  '/follow-ups': typeof FollowUpsRoute
  '/offers': typeof OffersRoute
  '/reports': typeof ReportsRoute
  '/rooms': typeof RoomsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buffet': typeof BuffetRoute
  '/conversations': typeof ConversationsRoute
  '/customers': typeof CustomersRoute
  '/enquiries': typeof EnquiriesRoute
  '/follow-ups': typeof FollowUpsRoute
  '/offers': typeof OffersRoute
  '/reports': typeof ReportsRoute
  '/rooms': typeof RoomsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buffet': typeof BuffetRoute
  '/conversations': typeof ConversationsRoute
  '/customers': typeof CustomersRoute
  '/enquiries': typeof EnquiriesRoute
  '/follow-ups': typeof FollowUpsRoute
  '/offers': typeof OffersRoute
  '/reports': typeof ReportsRoute
  '/rooms': typeof RoomsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buffet'
    | '/conversations'
    | '/customers'
    | '/enquiries'
    | '/follow-ups'
    | '/offers'
    | '/reports'
    | '/rooms'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buffet'
    | '/conversations'
    | '/customers'
    | '/enquiries'
    | '/follow-ups'
    | '/offers'
    | '/reports'
    | '/rooms'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/buffet'
    | '/conversations'
    | '/customers'
    | '/enquiries'
    | '/follow-ups'
    | '/offers'
    | '/reports'
    | '/rooms'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuffetRoute: typeof BuffetRoute
  ConversationsRoute: typeof ConversationsRoute
  CustomersRoute: typeof CustomersRoute
  EnquiriesRoute: typeof EnquiriesRoute
  FollowUpsRoute: typeof FollowUpsRoute
  OffersRoute: typeof OffersRoute
  ReportsRoute: typeof ReportsRoute
  RoomsRoute: typeof RoomsRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buffet': {
      id: '/buffet'
      path: '/buffet'
      fullPath: '/buffet'
      preLoaderRoute: typeof BuffetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations': {
      id: '/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof ConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquiries': {
      id: '/enquiries'
      path: '/enquiries'
      fullPath: '/enquiries'
      preLoaderRoute: typeof EnquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/follow-ups': {
      id: '/follow-ups'
      path: '/follow-ups'
      fullPath: '/follow-ups'
      preLoaderRoute: typeof FollowUpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuffetRoute: BuffetRoute,
  ConversationsRoute: ConversationsRoute,
  CustomersRoute: CustomersRoute,
  EnquiriesRoute: EnquiriesRoute,
  FollowUpsRoute: FollowUpsRoute,
  OffersRoute: OffersRoute,
  ReportsRoute: ReportsRoute,
  RoomsRoute: RoomsRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
