/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as BuffetRouteImport } from './routes/buffet'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as ConversationsRouteImport } from './routes/conversations'
import { Route as EnquiriesRouteImport } from './routes/enquiries'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as FollowUpsRouteImport } from './routes/follow-ups'
import { Route as HealthRouteImport } from './routes/health'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as StaffRouteImport } from './routes/staff'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const BuffetRoute = BuffetRouteImport.update({
  id: '/buffet',
  path: '/buffet',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsRoute = ConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const EnquiriesRoute = EnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowUpsRoute = FollowUpsRouteImport.update({
  id: '/follow-ups',
  path: '/follow-ups',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/buffet': typeof BuffetRoute
  '/campaigns': typeof CampaignsRoute
  '/config': typeof ConfigRoute
  '/conversations': typeof ConversationsRoute
  '/enquiries': typeof EnquiriesRoute
  '/feedback': typeof FeedbackRoute
  '/follow-ups': typeof FollowUpsRoute
  '/health': typeof HealthRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/offers': typeof OffersRoute
  '/queue': typeof QueueRoute
  '/staff': typeof StaffRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/buffet': typeof BuffetRoute
  '/campaigns': typeof CampaignsRoute
  '/config': typeof ConfigRoute
  '/conversations': typeof ConversationsRoute
  '/enquiries': typeof EnquiriesRoute
  '/feedback': typeof FeedbackRoute
  '/follow-ups': typeof FollowUpsRoute
  '/health': typeof HealthRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/offers': typeof OffersRoute
  '/queue': typeof QueueRoute
  '/staff': typeof StaffRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/buffet': typeof BuffetRoute
  '/campaigns': typeof CampaignsRoute
  '/config': typeof ConfigRoute
  '/conversations': typeof ConversationsRoute
  '/enquiries': typeof EnquiriesRoute
  '/feedback': typeof FeedbackRoute
  '/follow-ups': typeof FollowUpsRoute
  '/health': typeof HealthRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/offers': typeof OffersRoute
  '/queue': typeof QueueRoute
  '/staff': typeof StaffRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/buffet'
    | '/campaigns'
    | '/config'
    | '/conversations'
    | '/enquiries'
    | '/feedback'
    | '/follow-ups'
    | '/health'
    | '/knowledge'
    | '/login'
    | '/offers'
    | '/queue'
    | '/staff'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/buffet'
    | '/campaigns'
    | '/config'
    | '/conversations'
    | '/enquiries'
    | '/feedback'
    | '/follow-ups'
    | '/health'
    | '/knowledge'
    | '/login'
    | '/offers'
    | '/queue'
    | '/staff'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/buffet'
    | '/campaigns'
    | '/config'
    | '/conversations'
    | '/enquiries'
    | '/feedback'
    | '/follow-ups'
    | '/health'
    | '/knowledge'
    | '/login'
    | '/offers'
    | '/queue'
    | '/staff'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  BuffetRoute: typeof BuffetRoute
  CampaignsRoute: typeof CampaignsRoute
  ConfigRoute: typeof ConfigRoute
  ConversationsRoute: typeof ConversationsRoute
  EnquiriesRoute: typeof EnquiriesRoute
  FeedbackRoute: typeof FeedbackRoute
  FollowUpsRoute: typeof FollowUpsRoute
  HealthRoute: typeof HealthRoute
  KnowledgeRoute: typeof KnowledgeRoute
  LoginRoute: typeof LoginRoute
  OffersRoute: typeof OffersRoute
  QueueRoute: typeof QueueRoute
  StaffRoute: typeof StaffRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buffet': {
      id: '/buffet'
      path: '/buffet'
      fullPath: '/buffet'
      preLoaderRoute: typeof BuffetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations': {
      id: '/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof ConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquiries': {
      id: '/enquiries'
      path: '/enquiries'
      fullPath: '/enquiries'
      preLoaderRoute: typeof EnquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/follow-ups': {
      id: '/follow-ups'
      path: '/follow-ups'
      fullPath: '/follow-ups'
      preLoaderRoute: typeof FollowUpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  BuffetRoute: BuffetRoute,
  CampaignsRoute: CampaignsRoute,
  ConfigRoute: ConfigRoute,
  ConversationsRoute: ConversationsRoute,
  EnquiriesRoute: EnquiriesRoute,
  FeedbackRoute: FeedbackRoute,
  FollowUpsRoute: FollowUpsRoute,
  HealthRoute: HealthRoute,
  KnowledgeRoute: KnowledgeRoute,
  LoginRoute: LoginRoute,
  OffersRoute: OffersRoute,
  QueueRoute: QueueRoute,
  StaffRoute: StaffRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
